const lorem = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam maximus gravida maximus. Nulla sapien tellus, luctus non urna non, condimentum maximus tellus. Nulla dictum urna lectus, ac accumsan felis aliquam sed. Quisque odio diam, auctor in lobortis in, aliquam vitae massa. Nam pulvinar magna sed mauris fringilla egestas. Vestibulum ultricies condimentum leo at molestie. Praesent nec dui ut nunc consectetur fringilla. Aliquam vitae commodo dolor, a ultricies justo. Vivamus sit amet interdum risus, id fermentum odio. Curabitur cursus libero facilisis lacus pulvinar lacinia. Phasellus sapien est, vehicula eget scelerisque scelerisque, viverra et augue. Vestibulum semper mauris eget justo lobortis, quis feugiat magna tincidunt. Nulla ultrices pulvinar elit, porttitor efficitur dui ultricies vel.

            Suspendisse potenti. Quisque metus velit, accumsan non accumsan in, posuere eget urna. Sed vestibulum et augue id posuere. Duis malesuada nisl sit amet ligula euismod, sed commodo sem sodales. Nullam sollicitudin lacinia lectus, eget ultrices elit pretium et. Ut vitae consequat sem. Fusce sagittis quam ac tellus finibus, sit amet posuere mauris cursus. Suspendisse quis egestas justo. Quisque condimentum lacus nunc, sed hendrerit dui lacinia vel. Proin vitae sem ac ex ultrices consectetur.
            
            Etiam blandit aliquet maximus. Pellentesque congue scelerisque quam, ac malesuada erat faucibus at. Fusce malesuada ut enim sit amet dictum. Curabitur ut metus imperdiet, gravida dui vitae, varius velit. Integer orci leo, aliquam sit amet dolor eget, malesuada euismod lectus. Ut quis dolor ante. Mauris eu ante est. Integer ac eleifend leo, id commodo est.
            
            Fusce consequat tincidunt justo vel molestie. Donec in posuere ipsum. In hac habitasse platea dictumst. Fusce condimentum semper mollis. Cras vel porta mauris, at luctus tortor. Ut tincidunt elementum auctor. Curabitur posuere consectetur tellus eget vulputate. Sed ac elit non urna tempus volutpat. Phasellus blandit libero ac libero facilisis, nec venenatis est interdum. Nam facilisis elementum quam, at hendrerit nunc. Integer id auctor neque, nec fringilla quam. Mauris accumsan sed sapien id vehicula. Sed mauris eros, pulvinar sed lobortis eget, cursus at ligula.
            
            Cras lobortis mattis massa, vitae luctus augue gravida vel. Vestibulum efficitur velit eu aliquam congue. Etiam euismod neque iaculis sodales accumsan. Ut euismod nunc at erat accumsan bibendum. Nunc finibus maximus risus eu fermentum. Sed enim nisl, congue eget viverra vitae, placerat a magna. Duis et tellus ex. Pellentesque porttitor elit arcu, id bibendum nisi imperdiet a. Nulla luctus dui a nisi maximus varius. Maecenas nisi ligula, fermentum ac felis sit amet, luctus tristique leo. Fusce ac pretium ante, sit amet ultricies justo. Phasellus vel metus orci. Vivamus pretium mattis ex, sed pulvinar turpis gravida non. Nam sit amet convallis velit. Donec bibendum lacinia tempor. Donec dapibus ipsum leo, a dictum est blandit vel.
            
            Proin lobortis semper justo, et pretium elit vehicula at. Donec in turpis quis erat vulputate lacinia in eu leo. Maecenas suscipit faucibus vehicula. Vestibulum in elit sed arcu malesuada rutrum. Vivamus efficitur venenatis magna a rutrum. Nulla bibendum nunc sed imperdiet rutrum. Ut volutpat maximus eros, vitae porttitor urna. Etiam id nibh id dolor porta cursus at vitae augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
            
            Integer at augue rutrum, vulputate leo ut, interdum leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum orci orci, tempus id aliquam quis, porta et mi. Nulla facilisi. Ut quis odio odio. Nulla facilisi. Maecenas faucibus vitae dui eget condimentum.
            
            Donec et dui sit amet lacus posuere porttitor. Duis condimentum mattis hendrerit. Curabitur sed lectus iaculis enim tempor sagittis. Suspendisse pretium mattis nulla. Phasellus vel fermentum dolor. Suspendisse eros est, consequat ac lobortis sed, varius a quam. Duis interdum sem augue, at rhoncus tellus consequat vitae. Aliquam blandit ultrices erat, et ornare mauris. Duis quis gravida massa. Curabitur tortor purus, ultricies id lacinia vel, molestie ut neque. Curabitur eu odio ut lectus commodo laoreet ac nec lectus. Vestibulum pulvinar cursus tristique. Duis vitae dolor eu lorem consectetur feugiat. Morbi molestie vehicula nisl vitae ullamcorper.
            
            Curabitur tincidunt ultricies felis vel auctor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla facilisi. Integer imperdiet, enim sed sollicitudin viverra, ante justo dapibus mi, eget ultrices nunc lorem sit amet dolor. In interdum ullamcorper turpis nec mattis. Morbi cursus justo eu massa mollis, convallis convallis nibh mattis. Quisque nec auctor lorem, id aliquet massa. Integer a dignissim dui, in lacinia odio. Donec vulputate nunc lobortis metus fringilla, sit amet facilisis dolor auctor. Etiam porttitor odio eros, porttitor interdum sem commodo ac. Integer congue, est vel facilisis ultricies, enim enim pulvinar leo, sit amet sodales ligula mi in ipsum. Fusce sed nibh tincidunt, posuere urna ac, auctor turpis. Duis sit amet quam sit amet magna lacinia commodo.
            
            Aliquam ex elit, condimentum in massa sed, congue lacinia orci. Nullam a dui elit. Donec ut tempus leo. Nulla vel ligula tincidunt, congue odio et, blandit leo. Duis ut viverra nulla, in pulvinar nulla. Cras vitae odio faucibus, molestie lacus non, consectetur nunc. Donec vestibulum imperdiet mauris, ac volutpat ex tempor a. Curabitur interdum quam eu pellentesque dictum. Cras molestie erat a mauris tempor facilisis. Nam lobortis non nibh ac blandit. Nunc nec tortor elit. Donec vehicula scelerisque odio eu dignissim. Aenean semper varius dignissim. In sit amet neque pellentesque, consequat enim scelerisque, imperdiet velit. Donec placerat feugiat sagittis.
            
            Praesent sit amet lobortis diam. Maecenas nec rutrum quam, sed consequat ipsum. Proin elementum iaculis est. Sed maximus tellus nibh, dapibus aliquam metus egestas lacinia. Aliquam vehicula auctor hendrerit. Nunc egestas ultricies convallis. Nullam venenatis lacus at mauris bibendum, sed sollicitudin lorem gravida. Mauris eu mi odio. Praesent quam velit, cursus ut sapien vitae, gravida ornare lacus. Donec ut commodo urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus est felis, lacinia vel tempus id, imperdiet at lorem. Sed blandit, nulla vel sodales mollis, neque eros fringilla eros, nec vehicula urna quam ut justo. Mauris faucibus faucibus nibh quis luctus. Suspendisse vulputate aliquam erat, in imperdiet odio sollicitudin at.
            
            Suspendisse venenatis aliquet ligula at venenatis. Vestibulum vitae varius mauris, nec tincidunt lacus. Maecenas faucibus massa ut ipsum maximus, sed lacinia est interdum. Suspendisse luctus lacinia placerat. Sed a metus sed lorem vulputate posuere. Nulla at sollicitudin ex. Phasellus quis pretium justo. Ut imperdiet ullamcorper venenatis. Nullam pellentesque ornare tortor, et tristique massa rhoncus a. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In placerat semper nunc, sed rutrum quam tincidunt vitae. Integer eu odio tortor. Vivamus massa nulla, finibus et sollicitudin sit amet, luctus ac erat.
            
            Praesent vel neque quam. Maecenas dolor eros, consectetur sed augue et, tincidunt accumsan enim. Aliquam tincidunt non tellus in tristique. Donec vestibulum elit nibh, ut posuere ligula iaculis ut. Maecenas congue dictum facilisis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi et orci justo. Etiam varius finibus odio, quis malesuada leo consectetur in.
            
            Pellentesque at justo augue. Duis dui nisl, pulvinar sed nulla ultrices, laoreet tincidunt lectus. Aenean at pulvinar lacus. Aliquam fringilla varius tellus sit amet vestibulum. In condimentum orci sit amet risus hendrerit varius. Curabitur vehicula ornare nunc ultrices porttitor. Aliquam interdum ipsum eget leo tempor, sit amet fringilla lorem scelerisque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc leo nibh, scelerisque vitae diam at, euismod interdum leo. Aenean a nisi a mi varius ornare. Donec viverra felis a urna porttitor mollis. In ac neque vitae odio molestie lobortis. Nam consectetur nibh ut tortor finibus imperdiet. Phasellus urna sem, placerat vitae posuere at, rutrum eget nibh.
            
            Quisque vehicula urna et tortor suscipit dignissim. Etiam faucibus est a viverra hendrerit. Suspendisse sit amet metus dapibus, blandit dui sed, volutpat mi. Donec pretium varius ullamcorper. Mauris vitae vestibulum mauris. Sed iaculis dolor nec metus mattis, in dictum lorem viverra. Sed tempus faucibus lectus ac pharetra. Nunc rutrum elit ut est tristique, a viverra nunc ullamcorper. Ut at arcu eu sapien ultrices consectetur. Mauris blandit ultricies ultrices. Aenean neque neque, volutpat ac erat nec, congue aliquet ligula. Nam consectetur nisi vitae nulla elementum, eget pharetra nunc porta. Sed congue id nunc nec pellentesque. In luctus ultricies est, sed ultrices magna viverra eget.
            
            Proin blandit, eros vel mollis eleifend, mi lacus eleifend quam, ac bibendum magna nisi porttitor felis. Praesent dignissim blandit rhoncus. Curabitur fringilla egestas vulputate. Integer vulputate mollis lacus, quis placerat justo fringilla et. Nam elementum velit lectus, non aliquam leo dictum id. Suspendisse eget mollis dui. Proin mauris urna, rhoncus et hendrerit ut, accumsan sit amet neque. Vestibulum non lobortis velit.
            
            Nullam nulla lacus, interdum at molestie nec, ullamcorper eu lorem. Nulla vitae leo quam. Morbi ac tellus non sem commodo ultrices. Etiam quis lobortis ante. Mauris ultricies eu sem eget ultricies. Duis eget augue nec diam vehicula porta non vitae nisi. Suspendisse malesuada, magna a faucibus sollicitudin, dolor metus molestie mi, vitae ullamcorper lacus tortor ac arcu.
            
            Sed non quam in massa sagittis egestas non eget sem. Praesent vel cursus magna. Phasellus in eros vel dui imperdiet gravida. Sed facilisis lobortis massa. Fusce egestas sollicitudin odio, id lacinia sapien convallis vitae. Proin porta, ex eu mollis pharetra, justo leo sodales justo, ut tempus sapien mauris rutrum augue. Nam id vulputate lacus. Nunc tincidunt ex elementum pellentesque tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer maximus a nibh et pulvinar. Phasellus tempus urna et ligula dignissim congue.
            
            Mauris feugiat tincidunt tristique. Ut ultrices, lacus sit amet aliquet suscipit, elit orci mollis neque, ut vulputate arcu tortor ac sem. In vulputate tempor sem eget facilisis. Cras vehicula, diam vel tristique consequat, libero justo varius mi, eget consectetur libero arcu vel arcu. Cras porta pellentesque elit, sit amet dictum augue pretium id. Ut faucibus ante at blandit aliquam. Quisque vitae posuere dui, id cursus erat. Phasellus ornare risus vel efficitur dictum. Fusce sed ultricies magna. Fusce hendrerit dapibus quam quis lobortis. Maecenas ullamcorper congue justo.
            
            Etiam malesuada semper commodo. Cras fringilla molestie nisl, vitae semper nunc ultrices non. Pellentesque egestas sem at porttitor pretium. Nullam posuere quam vel consequat varius. Nulla facilisi. Proin nulla dolor, vulputate quis enim at, sodales vehicula diam. In lobortis dui a mi venenatis, et volutpat ipsum feugiat. Etiam convallis leo sed enim mattis, quis auctor lacus ultrices. Nunc convallis nulla eu leo euismod egestas sed at turpis. Donec faucibus est sit amet fermentum hendrerit. Etiam at nulla nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ac convallis enim. Nulla facilisi.`;

document.querySelector("#lorem").innerText = lorem.replaceAll("\n", " ").repeat(5);